name: API User CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  MONGODB_4_0: 4.0.13


defaults:
  run:
    working-directory: user-api

jobs:
  tests:
    name: Testes de Unidade de Integração
    runs-on: ubuntu-latest
    strategy:
      matrix:
        MONGODB: [${{ env.MONGODB_4_0 }}]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.MONGODB }}
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: user-api/package-lock.json
      - run: npm ci
      - run: npm test -- --forceExit


  lint:
    name: Análise estática
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: user-api/package-lock.json
      - run: npm ci
      - run: npm run lint

  vulnerability:
    name: Teste de vulnerabilidade
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: user-api/package-lock.json
      - run: npm ci
      - run: npm audit